2025-08-24 10:04:41.752 +03:00 [ERR] An error has occurred traceId: 0HNF2RHS1NTLV:00000004
System.InvalidOperationException: Project with this title already exists
   at TaskTrackerClean.Application.Services.ProjectService.CreateAsync(CreateProjectDto dto, String createdBy) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\TaskTrackerClean.Application\Services\ProjectService.cs:line 27
   at TaskTrackerClean.API.Controllers.ProjectsController.Create(CreateProjectDto dto) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\TaskTrackerClean.API\Controllers\ProjectsController.cs:line 24
   at lambda_method8(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at TaskTrackerClean.API.Middlewares.ExceptionHandlingMiddleware.Invoke(HttpContext context) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\TaskTrackerClean.API\Middlewares\ExceptionHandlingMiddleware.cs:line 28
2025-08-24 10:04:46.128 +03:00 [ERR] An error has occurred traceId: 0HNF2RHS1NTLV:00000005
System.InvalidOperationException: Project with this title already exists
   at TaskTrackerClean.Application.Services.ProjectService.CreateAsync(CreateProjectDto dto, String createdBy) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\TaskTrackerClean.Application\Services\ProjectService.cs:line 27
   at TaskTrackerClean.API.Controllers.ProjectsController.Create(CreateProjectDto dto) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\TaskTrackerClean.API\Controllers\ProjectsController.cs:line 24
   at lambda_method8(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at TaskTrackerClean.API.Middlewares.ExceptionHandlingMiddleware.Invoke(HttpContext context) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\TaskTrackerClean.API\Middlewares\ExceptionHandlingMiddleware.cs:line 28
2025-08-24 10:56:16.629 +03:00 [ERR] An error has occurred traceId: 0HNF2SECMIHM1:00000003
System.InvalidOperationException: Project with this title already exists
   at TaskTrackerClean.Application.Services.ProjectService.CreateAsync(CreateProjectDto dto, String createdBy) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\Microservices\TaskTrackerCleanService\TaskTrackerClean.Application\Services\ProjectService.cs:line 27
   at TaskTrackerClean.API.Controllers.ProjectsController.Create(CreateProjectDto dto) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\Microservices\TaskTrackerCleanService\TaskTrackerClean.API\Controllers\ProjectsController.cs:line 24
   at lambda_method8(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at TaskTrackerClean.API.Middlewares.ExceptionHandlingMiddleware.Invoke(HttpContext context) in C:\Users\Sedra\Documents\My .Net Projects\TaskTrackerClean\src\Microservices\TaskTrackerCleanService\TaskTrackerClean.API\Middlewares\ExceptionHandlingMiddleware.cs:line 28
